<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="ranger_mini_complete">

  <!-- Constants -->
  <xacro:property name="M_PI" value="3.14159265359"/>

  <!-- Base dimensions (Ranger Mini 3.0 approximate dimensions) -->
  <xacro:property name="base_length" value="0.70"/>
  <xacro:property name="base_width" value="0.70"/>
  <xacro:property name="base_height" value="0.25"/>

  <!-- Sensor mounting positions -->
  <xacro:property name="lidar_x" value="0.0"/>
  <xacro:property name="lidar_y" value="0.0"/>
  <xacro:property name="lidar_z" value="0.70"/>

  <xacro:property name="camera_x" value="0.20"/>
  <xacro:property name="camera_y" value="0.0"/>
  <xacro:property name="camera_z" value="0.50"/>

  <xacro:property name="arm_x" value="0.0"/>
  <xacro:property name="arm_y" value="0.0"/>
  <xacro:property name="arm_z" value="0.30"/>

  <!-- Base link -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <material name="gray">
        <color rgba="0.5 0.5 0.5 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="50.0"/>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <inertia ixx="2.042" ixy="0.0" ixz="0.0"
               iyy="2.042" iyz="0.0"
               izz="4.083"/>
    </inertial>
  </link>

  <!-- Footprint link (for navigation) -->
  <link name="base_footprint"/>

  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 0.10" rpy="0 0 0"/>
  </joint>

  <!-- LiDAR Link (Livox Mid-360) -->
  <link name="lidar_link">
    <visual>
      <geometry>
        <cylinder radius="0.05" length="0.08"/>
      </geometry>
      <material name="black">
        <color rgba="0.1 0.1 0.1 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.05" length="0.08"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.3"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001"/>
    </inertial>
  </link>

  <joint name="lidar_mount" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="${lidar_x} ${lidar_y} ${lidar_z}" rpy="0 0 0"/>
  </joint>

  <!-- Camera Link (RealSense D435) -->
  <link name="camera_link">
    <visual>
      <geometry>
        <box size="0.090 0.025 0.025"/>
      </geometry>
      <material name="silver">
        <color rgba="0.8 0.8 0.8 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="0.090 0.025 0.025"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.072"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
               iyy="0.0001" iyz="0.0"
               izz="0.0001"/>
    </inertial>
  </link>

  <joint name="camera_mount" type="fixed">
    <parent link="base_link"/>
    <child link="camera_link"/>
    <origin xyz="${camera_x} ${camera_y} ${camera_z}" rpy="0 0 0"/>
  </joint>

  <!-- Camera depth optical frame -->
  <link name="camera_depth_optical_frame"/>

  <joint name="camera_depth_optical_joint" type="fixed">
    <parent link="camera_link"/>
    <child link="camera_depth_optical_frame"/>
    <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}"/>
  </joint>

  <!-- Camera color optical frame -->
  <link name="camera_color_optical_frame"/>

  <joint name="camera_color_optical_joint" type="fixed">
    <parent link="camera_link"/>
    <child link="camera_color_optical_frame"/>
    <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}"/>
  </joint>

  <!-- PiPER Arm Base Link (placeholder - actual arm from piper_ros) -->
  <link name="piper_base_link">
    <visual>
      <geometry>
        <cylinder radius="0.06" length="0.10"/>
      </geometry>
      <material name="blue">
        <color rgba="0.2 0.2 0.8 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.06" length="0.10"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="1.0"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0"
               iyy="0.01" iyz="0.0"
               izz="0.01"/>
    </inertial>
  </link>

  <joint name="arm_mount" type="fixed">
    <parent link="base_link"/>
    <child link="piper_base_link"/>
    <origin xyz="${arm_x} ${arm_y} ${arm_z}" rpy="0 0 0"/>
  </joint>

</robot>
